; Manavalan, P. and Ponnnuswamy, P. K. (1978) Hydrophobic
; character of amino acid residues in globular proteins.
; Nature (London) 275, 673-674
;
; Taken from Von Heijne, Sequence analysis in Molecular Biology
; pg. 99
Ala	13.0
Cys	14.6
Asp	10.9
Glu	11.9
Phe	14.0
Gly	12.4
His	12.2
Ile	15.7
Lys	11.4
Leu	14.9
Met	14.4
Asn	11.4
Pro	11.4
Gln	11.8
Arg	11.7
Ser	11.2
Thr	11.7
Val	15.7
Trp	13.9
Tyr	13.4
